### ISSUE TITLE
Update rubicure v3

### ISSUE THREAD

**Issue by 3socha** [greymd/cureutils#31]
cureutils 1.4.0 が ruby 2.7.4 で動作しなくなりました。

<details>

```sh
$ cure girls
Traceback (most recent call last):
        50: from /usr/local/bin/cure:23:in `<main>'
        49: from /usr/local/bin/cure:23:in `load'
        48: from /var/lib/gems/2.7.0/gems/cureutils-1.4.0/bin/cure:7:in `<top (required)>'
        47: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        46: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        45: from /var/lib/gems/2.7.0/gems/cureutils-1.4.0/lib/cureutils.rb:3:in `<top (required)>'
        44: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        43: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        42: from /var/lib/gems/2.7.0/gems/cureutils-1.4.0/lib/cureutils/cli.rb:14:in `<top (required)>'
        41: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        40: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        39: from /var/lib/gems/2.7.0/gems/rubicure-2.1.5/lib/rubicure.rb:20:in `<top (required)>'
        38: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        37: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        36: from /var/lib/gems/2.7.0/gems/rubicure-2.1.5/lib/rubicure/girl.rb:1:in `<top (required)>'
        35: from /var/lib/gems/2.7.0/gems/rubicure-2.1.5/lib/rubicure/girl.rb:7:in `<module:Rubicure>'
        34: from /var/lib/gems/2.7.0/gems/rubicure-2.1.5/lib/rubicure/girl.rb:250:in `<class:Girl>'
        33: from /var/lib/gems/2.7.0/gems/rubicure-2.1.5/lib/rubicure/girl.rb:244:in `colors'
        32: from /var/lib/gems/2.7.0/gems/rubicure-2.1.5/lib/rubicure/girl.rb:218:in `config'
        31: from /var/lib/gems/2.7.0/gems/sengiri_yaml-1.0.0/lib/sengiri_yaml.rb:11:in `load_dir'
        30: from /var/lib/gems/2.7.0/gems/sengiri_yaml-1.0.0/lib/sengiri_yaml/loader.rb:17:in `load_dir'
        29: from /usr/lib/ruby/2.7.0/psych.rb:360:in `safe_load'
        28: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
        27: from /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
        26: from /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
        25: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:313:in `visit_Psych_Nodes_Document'
        24: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
        23: from /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
        22: from /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
        21: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
        20: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `revive_hash'
        19: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each_slice'
        18: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each'
        17: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:340:in `block in revive_hash'
        16: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
        15: from /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
        14: from /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
        13: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
        12: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `revive_hash'
        11: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each_slice'
        10: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each'
         9: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:340:in `block in revive_hash'
         8: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
         7: from /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
         6: from /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
         5: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
         4: from /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:60:in `deserialize'
         3: from /usr/lib/ruby/2.7.0/psych/scalar_scanner.rb:60:in `tokenize'
         2: from /usr/lib/ruby/2.7.0/psych/class_loader.rb:39:in `block (2 levels) in <class:ClassLoader>'
         1: from /usr/lib/ruby/2.7.0/psych/class_loader.rb:28:in `load'
/usr/lib/ruby/2.7.0/psych/class_loader.rb:97:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
```

```sh
$ ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [aarch64-linux-gnu]
```

</details>

cureutils が依存する `rubicure` (2.1.5) -> `sengiri_yaml` が 1.0.0 に更新され、その際に `YAML.safe_load()` が使われるようになり、信頼されない YAML のロードがブロックされているようです。
`rubicure` 3.0.0 で対応されているようなので、更新していただけないでしょうか。

参考：

- https://sue445.hatenablog.com/entry/2021/12/31/211404
- https://github.com/sue445/sengiri_yaml/pull/26
- https://techlife.cookpad.com/entry/2021/12/25/220002

**Comment by greymd** [comment]
ご連絡ありがとうございます。大変助かります。
こちら、対応しました。
https://rubygems.org/gems/cureutils/versions/1.5.0
https://github.com/greymd/cureutils/releases/tag/v1.5.0

**Comment by 3socha** [comment]
ありがとうございます。v1.5.0 で正常に動作しました！
